# Generated by Django 6.0.7 on 2026-07-11 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='storicoeventi',
            constraint=models.UniqueConstraint(fields=('doy', 'event_index'), name='vincolo_eventi'),
        ),
    ]
